# Change these first
owner: mauribesson # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
 ####  DEV
 # - name: DEV - API -- - Transact Api -    
 #   url: http://52.143.251.96/swagger
 # - name: DEV - API - Ticket Api
 #   url: http://13.86.126.10/swagger    
 # - name: DEV - API - Eflow Auth
 #   url: http://52.143.249.28/swagger
 # - name: DEV - API - Appointment Api
 #   url: http://13.89.107.12/swagger
 # - name: DEV - API - Annucement[VER estaba caido al probar ..] 
 #   url: http://40.89.248.129/swagger
    
 #  VQs PROD 
  - name: VQ PROD AR
    url: http://demoarg.sidesys.com.ar/virtualqueue/index.html
    maxResponseTime: 60000
    
  #  - name: VQ PROD RD --
  #    url: http://demord.sidesys.com.do:8080/virtualqueue/index.html
  #    maxResponseTime: 60000
  
  - name: VQ PROD CO
    url: http://demord.sidesys.com.do:8080/virtualqueue_CO/index.html
    maxResponseTime: 60000

  - name: VQ PROD MX
    url: http://demomx.sidesys.com.mx/virtualqueue/index.html
    maxResponseTime: 60000
     
  - name: VQ PROD SV 
    url: https://demolatam.sidesys.com.ar/VirtualQueue_SV/index.html
    maxResponseTime: 60000

  - name: VQ PROD GT 
    url: https://demolatam.sidesys.com.ar/VirtualQueue_GT/index.html
    maxResponseTime: 60000
    
  - name: VQ PROD CR 
    url: http://democr.sidesys.co.cr/virtualqueue/index.html
    maxResponseTime: 60000
     
     
 # APIs Backend Publico PROD
  - name: API transact - PROD
    url: https://transact.prod.api.eflow.com.ar/swagger
    maxResponseTime: 60000

  - name: API ticket - PROD
    url: https://ticket.prod.api.eflow.com.ar/swagger
    maxResponseTime: 60000

  - name: API auth - PROD
    url: https://auth.prod.api.eflow.com.ar/swagger
    maxResponseTime: 60000

  - name: API appointment - PROD
    url: https://appointment.prod.api.eflow.com.ar/swagger
    maxResponseTime: 60000

  - name: API announcement - PROD
    url: https://announcement.prod.api.eflow.com.ar/swagger
    maxResponseTime: 60000

  
# APIs Backend Publico TEST
  #- name: API transact - TEST
   # url: http://52.154.219.177/swagger
    #maxResponseTime: 60000

  #- name: API ticket - TEST
   # url: http://20.118.2.237/swagger
    #maxResponseTime: 60000

  #- name: API auth - TEST
   # url: http://20.118.2.6/swagger
    #maxResponseTime: 60000

  #- name: API appointment - TEST
    #url: http://20.118.0.8/swagger
    #maxResponseTime: 60000

  #- name: API announcement - TEST
   # url:  http://13.86.127.46/swagger
    #maxResponseTime: 60000
    
      
assignees:
  - mauribesson
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime - APP PUBLICA
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
